spring:
  application:
    name: spring-data-redis-demo
  data:
    redis:
      host: 127.0.0.1
      port: 6388
      password: 123456
      lettuce:
        pool:
          max-active: 8  #最大连接
          max-idle: 8   #最大空闲连接
          min-idle: 0   #最小空闲连接
          max-wait: 100ms #连接等待时间